@host = https://localhost:5001
@token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMjI1MDZmOC0wMDkwLTQ0ZDMtOGI4My1jMjM5YzM2NTU1OGQiLCJqdGkiOiI2MDBhNzBlNi04OGY0LTRkNTAtODY2Yi01OWY3NDIzZmQyMWIiLCJnaXZlbl9uYW1lIjoiSmFpbWUiLCJmYW1pbHlfbmFtZSI6IkphcmFtaWxsbyIsIm5iZiI6MTcxNzI1MjgzNCwiZXhwIjoxNzE3MjUzNDM0LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.w72DMoXQC9hJZXX7XzcAzuYMjIFqzOjWOCPlvK2ZMPk

GET {{host}}/api/dinners
Authorization: Bearer {{token}}
